DROP SCHEMA PUBLIC CASCADE;
CREATE TABLE account (id BIGINT NOT NULL, balance DECIMAL(19,2) DEFAULT 0.00, PRIMARY KEY(id));
INSERT INTO account (id, balance) VALUES (0, 999.99);
INSERT INTO account (id) VALUES (1);